INSERT INTO TBL_MEMBER
VALUES (SEQ_MEMBER.NEXTVAL, 'test@test.com', '1234', '테스트사용자', 'USER', SYSDATE, NULL);

INSERT INTO TBL_MEMBER
VALUES (SEQ_MEMBER.NEXTVAL, 'demo@test.com', '1234', '데모사용자', 'USER', SYSDATE, NULL);

INSERT INTO TBL_ACCOUNT
VALUES (SEQ_ACCOUNT.NEXTVAL, 1, '신한은행', '생활비 계좌', '110-111-111111', 9055000, 'ACTIVE', SYSDATE, NULL);

INSERT INTO TBL_ACCOUNT
VALUES (SEQ_ACCOUNT.NEXTVAL, 1, '카카오뱅크', '비상금 계좌', '3333-22-1111111', 315000, 'ACTIVE', SYSDATE, NULL);

INSERT INTO TBL_ACCOUNT
VALUES (SEQ_ACCOUNT.NEXTVAL, 1, '토스뱅크', '저축 계좌', '1000-2000-3000', 977000, 'ACTIVE', SYSDATE, NULL);

INSERT INTO TBL_ACCOUNT
VALUES (SEQ_ACCOUNT.NEXTVAL, 2, '국민은행', '데모 계좌', '999-000-111111', 4285000, 'ACTIVE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '월급', 'INCOME', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '보너스', 'INCOME', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '용돈', 'INCOME', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '이자', 'INCOME', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '식비', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '교통비', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '쇼핑', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '주거비', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '통신비', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '문화생활', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '의료비', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 1, '교육비', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 2, '월급', 'INCOME', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 2, '식비', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, 2, '교통비', 'EXPENSE', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 8, 'EXPENSE', 650000, TO_DATE('2026-01-02', 'YYYY-MM-DD'), '월세', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 5, 'EXPENSE', 320000, TO_DATE('2026-01-05', 'YYYY-MM-DD'), '식비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 3, 'INCOME', 200000, TO_DATE('2026-01-05', 'YYYY-MM-DD'), '용돈', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 6, 'EXPENSE', 85000, TO_DATE('2026-01-08', 'YYYY-MM-DD'), '교통비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 3, 2, 'INCOME', 500000, TO_DATE('2026-01-10', 'YYYY-MM-DD'), '저축 입금', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 9, 'EXPENSE', 75000, TO_DATE('2026-01-11', 'YYYY-MM-DD'), '통신비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 7, 'EXPENSE', 80000, TO_DATE('2026-01-13', 'YYYY-MM-DD'), '온라인 쇼핑', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 10, 'EXPENSE', 120000, TO_DATE('2026-01-14', 'YYYY-MM-DD'), '영화 및 외식', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 1, 'INCOME', 2800000, TO_DATE('2026-01-25', 'YYYY-MM-DD'), '1월 급여', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 8, 'EXPENSE', 650000, TO_DATE('2026-02-02', 'YYYY-MM-DD'), '월세', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 5, 'EXPENSE', 350000, TO_DATE('2026-02-05', 'YYYY-MM-DD'), '식비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 3, 'INCOME', 100000, TO_DATE('2026-02-05', 'YYYY-MM-DD'), '용돈', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 6, 'EXPENSE', 90000, TO_DATE('2026-02-08', 'YYYY-MM-DD'), '교통비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 7, 'EXPENSE', 240000, TO_DATE('2026-02-11', 'YYYY-MM-DD'), '의류 구매', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 9, 'EXPENSE', 75000, TO_DATE('2026-02-14', 'YYYY-MM-DD'), '통신비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 10, 'EXPENSE', 50000, TO_DATE('2026-02-14', 'YYYY-MM-DD'), '영화', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 5, 'EXPENSE', 45000, TO_DATE('2026-02-22', 'YYYY-MM-DD'), '외식', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 1, 'INCOME', 2800000, TO_DATE('2026-02-25', 'YYYY-MM-DD'), '2월 급여', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 3, 4, 'INCOME', 8000, TO_DATE('2026-02-28', 'YYYY-MM-DD'), '예금 이자', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 2, 'INCOME', 500000, TO_DATE('2026-03-02', 'YYYY-MM-DD'), '분기 보너스', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 8, 'EXPENSE', 650000, TO_DATE('2026-03-05', 'YYYY-MM-DD'), '월세', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 3, 'INCOME', 150000, TO_DATE('2026-03-05', 'YYYY-MM-DD'), '용돈', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 5, 'EXPENSE', 330000, TO_DATE('2026-03-08', 'YYYY-MM-DD'), '식비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 3, 2, 'INCOME', 300000, TO_DATE('2026-03-10', 'YYYY-MM-DD'), '저축 입금', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 12, 'EXPENSE', 180000, TO_DATE('2026-03-11', 'YYYY-MM-DD'), '온라인 강의', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 11, 'EXPENSE', 60000, TO_DATE('2026-03-14', 'YYYY-MM-DD'), '병원 진료', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 7, 'EXPENSE', 100000, TO_DATE('2026-03-16', 'YYYY-MM-DD'), '가방 구매', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 10, 'EXPENSE', 95000, TO_DATE('2026-03-17', 'YYYY-MM-DD'), '문화생활', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 3, 12, 'EXPENSE', 50000, TO_DATE('2026-03-21', 'YYYY-MM-DD'), '교재 구매', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 1, 'INCOME', 2800000, TO_DATE('2026-03-25', 'YYYY-MM-DD'), '3월 급여', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 4, 'INCOME', 5000, TO_DATE('2026-03-28', 'YYYY-MM-DD'), '이자', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 8, 'EXPENSE', 650000, TO_DATE('2026-04-02', 'YYYY-MM-DD'), '월세', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 5, 'EXPENSE', 370000, TO_DATE('2026-04-05', 'YYYY-MM-DD'), '식비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 3, 'INCOME', 100000, TO_DATE('2026-04-05', 'YYYY-MM-DD'), '용돈', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 6, 'EXPENSE', 90000, TO_DATE('2026-04-08', 'YYYY-MM-DD'), '교통비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 7, 'EXPENSE', 180000, TO_DATE('2026-04-11', 'YYYY-MM-DD'), '생활용품', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 9, 'EXPENSE', 75000, TO_DATE('2026-04-14', 'YYYY-MM-DD'), '통신비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 10, 'EXPENSE', 130000, TO_DATE('2026-04-17', 'YYYY-MM-DD'), '공연 관람', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 11, 'EXPENSE', 40000, TO_DATE('2026-04-20', 'YYYY-MM-DD'), '약국', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 1, 'INCOME', 2800000, TO_DATE('2026-04-25', 'YYYY-MM-DD'), '4월 급여', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 3, 4, 'INCOME', 9000, TO_DATE('2026-04-28', 'YYYY-MM-DD'), '예금 이자', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 8, 'EXPENSE', 650000, TO_DATE('2026-05-02', 'YYYY-MM-DD'), '월세', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 5, 'EXPENSE', 410000, TO_DATE('2026-05-05', 'YYYY-MM-DD'), '식비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 3, 'INCOME', 100000, TO_DATE('2026-05-05', 'YYYY-MM-DD'), '용돈', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 6, 'EXPENSE', 95000, TO_DATE('2026-05-08', 'YYYY-MM-DD'), '교통비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 3, 2, 'INCOME', 300000, TO_DATE('2026-05-10', 'YYYY-MM-DD'), '저축 입금', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 4, 14, 'EXPENSE', 280000, TO_DATE('2026-05-10', 'YYYY-MM-DD'), '식비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 11, 'EXPENSE', 120000, TO_DATE('2026-05-11', 'YYYY-MM-DD'), '치과 진료', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 4, 15, 'EXPENSE', 65000, TO_DATE('2026-05-12', 'YYYY-MM-DD'), '교통비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 12, 'EXPENSE', 200000, TO_DATE('2026-05-14', 'YYYY-MM-DD'), '자격증 강의', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 10, 'EXPENSE', 70000, TO_DATE('2026-05-19', 'YYYY-MM-DD'), '공연', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 1, 'INCOME', 2800000, TO_DATE('2026-05-25', 'YYYY-MM-DD'), '5월 급여', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 4, 13, 'INCOME', 2500000, TO_DATE('2026-05-25', 'YYYY-MM-DD'), '5월 급여', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 8, 'EXPENSE', 650000, TO_DATE('2026-06-02', 'YYYY-MM-DD'), '월세', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 5, 'EXPENSE', 290000, TO_DATE('2026-06-05', 'YYYY-MM-DD'), '식비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 3, 'INCOME', 100000, TO_DATE('2026-06-05', 'YYYY-MM-DD'), '용돈', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 6, 'EXPENSE', 80000, TO_DATE('2026-06-08', 'YYYY-MM-DD'), '교통비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 4, 14, 'EXPENSE', 300000, TO_DATE('2026-06-10', 'YYYY-MM-DD'), '식비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 9, 'EXPENSE', 75000, TO_DATE('2026-06-11', 'YYYY-MM-DD'), '통신비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 4, 15, 'EXPENSE', 70000, TO_DATE('2026-06-12', 'YYYY-MM-DD'), '교통비', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 10, 'EXPENSE', 60000, TO_DATE('2026-06-14', 'YYYY-MM-DD'), '카페 및 영화', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 7, 'EXPENSE', 60000, TO_DATE('2026-06-15', 'YYYY-MM-DD'), '쇼핑', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 7, 'EXPENSE', 150000, TO_DATE('2026-06-17', 'YYYY-MM-DD'), '전자기기 소모품', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 3, 12, 'EXPENSE', 100000, TO_DATE('2026-06-22', 'YYYY-MM-DD'), '시험 응시료', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 1, 1, 'INCOME', 2800000, TO_DATE('2026-06-25', 'YYYY-MM-DD'), '6월 급여', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 4, 13, 'INCOME', 2500000, TO_DATE('2026-06-25', 'YYYY-MM-DD'), '6월 급여', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 2, 4, 'INCOME', 5000, TO_DATE('2026-06-28', 'YYYY-MM-DD'), '이자', SYSDATE, NULL);

INSERT INTO TBL_TRANSACTION
VALUES (SEQ_TRANSACTION.NEXTVAL, 3, 4, 'INCOME', 10000, TO_DATE('2026-06-28', 'YYYY-MM-DD'), '예금 이자', SYSDATE, NULL);

COMMIT;
