-- 계좌 등록
INSERT INTO TBL_ACCOUNT
VALUES (SEQ_ACCOUNT.NEXTVAL, ?, ?, ?, ?, ?, 'ACTIVE', SYSDATE, NULL)

/* MEMBER_ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE */



-- 내 계좌 목록 조회
SELECT ID, MEMBER_ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE, ACCOUNT_STATUS, CREATED_AT, UPDATED_AT
FROM TBL_ACCOUNT
WHERE MEMBER_ID = ?
AND ACCOUNT_STATUS = 'ACTIVE'
ORDER BY ID

/* MEMBER_ID */



-- 특정 계좌 조회
SELECT ID, MEMBER_ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE, ACCOUNT_STATUS, CREATED_AT, UPDATED_AT
FROM TBL_ACCOUNT
WHERE ID = ?
AND MEMBER_ID = ?
AND ACCOUNT_STATUS = 'ACTIVE'

/* ACCOUNT_ID, MEMBER_ID */



-- 계좌 수정
UPDATE TBL_ACCOUNT
SET BANK_NAME = ?,
    ACCOUNT_NAME = ?,
    ACCOUNT_NUMBER = ?,
    UPDATED_AT = SYSDATE
WHERE ID = ?
AND MEMBER_ID = ?
AND ACCOUNT_STATUS = 'ACTIVE'

/* BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, ACCOUNT_ID, MEMBER_ID */



-- 계좌 삭제 처리
UPDATE TBL_ACCOUNT
SET ACCOUNT_STATUS = 'DELETED',
    UPDATED_AT = SYSDATE
WHERE ID = ?
AND MEMBER_ID = ?
AND ACCOUNT_STATUS = 'ACTIVE'

/* ACCOUNT_ID, MEMBER_ID */



-- 계좌 잔액 증가
UPDATE TBL_ACCOUNT
SET BALANCE = BALANCE + ?,
    UPDATED_AT = SYSDATE
WHERE ID = ?
AND MEMBER_ID = ?
AND ACCOUNT_STATUS = 'ACTIVE'

/* AMOUNT, ACCOUNT_ID, MEMBER_ID */



-- 계좌 잔액 감소
UPDATE TBL_ACCOUNT
SET BALANCE = BALANCE - ?,
    UPDATED_AT = SYSDATE
WHERE ID = ?
AND MEMBER_ID = ?
AND ACCOUNT_STATUS = 'ACTIVE'
AND BALANCE >= ?

/* AMOUNT, ACCOUNT_ID, MEMBER_ID, AMOUNT */



-- 내 전체 자산 잔액 조회
SELECT NVL(SUM(BALANCE), 0) AS TOTAL_BALANCE
FROM TBL_ACCOUNT
WHERE MEMBER_ID = ?
AND ACCOUNT_STATUS = 'ACTIVE'

/* MEMBER_ID */



-- 계좌별 잔액 조회
SELECT ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE
FROM TBL_ACCOUNT
WHERE MEMBER_ID = ?
AND ACCOUNT_STATUS = 'ACTIVE'
ORDER BY ID

/* MEMBER_ID */
