-- 예산 등록
INSERT INTO TBL_BUDGET
VALUES (SEQ_BUDGET.NEXTVAL, ?, ?, ?, ?, SYSDATE, NULL)

/* MEMBER_ID, CATEGORY_ID, BUDGET_MONTH, BUDGET_AMOUNT */



-- 내 예산 목록 조회
SELECT B.ID,
       B.MEMBER_ID,
       B.CATEGORY_ID,
       C.CATEGORY_NAME,
       B.BUDGET_MONTH,
       B.BUDGET_AMOUNT,
       B.CREATED_AT,
       B.UPDATED_AT
FROM TBL_BUDGET B
JOIN TBL_CATEGORY C
    ON B.CATEGORY_ID = C.ID
WHERE B.MEMBER_ID = ?
ORDER BY B.BUDGET_MONTH DESC, C.CATEGORY_NAME

/* MEMBER_ID */



-- 특정 월 예산 조회
SELECT B.ID,
       B.MEMBER_ID,
       B.CATEGORY_ID,
       C.CATEGORY_NAME,
       B.BUDGET_MONTH,
       B.BUDGET_AMOUNT,
       B.CREATED_AT,
       B.UPDATED_AT
FROM TBL_BUDGET B
JOIN TBL_CATEGORY C
    ON B.CATEGORY_ID = C.ID
WHERE B.MEMBER_ID = ?
AND B.BUDGET_MONTH = ?
ORDER BY C.CATEGORY_NAME

/* MEMBER_ID, BUDGET_MONTH */



-- 특정 예산 조회
SELECT B.ID,
       B.MEMBER_ID,
       B.CATEGORY_ID,
       C.CATEGORY_NAME,
       B.BUDGET_MONTH,
       B.BUDGET_AMOUNT
FROM TBL_BUDGET B
JOIN TBL_CATEGORY C
    ON B.CATEGORY_ID = C.ID
WHERE B.ID = ?
AND B.MEMBER_ID = ?

/* BUDGET_ID, MEMBER_ID */



-- 예산 수정
UPDATE TBL_BUDGET
SET BUDGET_AMOUNT = ?,
    UPDATED_AT = SYSDATE
WHERE ID = ?
AND MEMBER_ID = ?

/* BUDGET_AMOUNT, BUDGET_ID, MEMBER_ID */



-- 예산 삭제
DELETE FROM TBL_BUDGET
WHERE ID = ?
AND MEMBER_ID = ?

/* BUDGET_ID, MEMBER_ID */



-- 예산 대비 사용률 조회
SELECT C.CATEGORY_NAME,
       B.BUDGET_MONTH,
       B.BUDGET_AMOUNT,
       NVL(SUM(T.AMOUNT), 0) AS USED_AMOUNT,
       B.BUDGET_AMOUNT - NVL(SUM(T.AMOUNT), 0) AS REMAIN_AMOUNT,
       ROUND(NVL(SUM(T.AMOUNT), 0) / B.BUDGET_AMOUNT * 100, 1) AS USED_RATE
FROM TBL_BUDGET B
JOIN TBL_CATEGORY C
    ON B.CATEGORY_ID = C.ID
LEFT JOIN TBL_TRANSACTION T
    ON T.CATEGORY_ID = B.CATEGORY_ID
    AND T.TRANSACTION_TYPE = 'EXPENSE'
    AND TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') = B.BUDGET_MONTH
WHERE B.MEMBER_ID = ?
AND B.BUDGET_MONTH = ?
GROUP BY C.CATEGORY_NAME,
         B.BUDGET_MONTH,
         B.BUDGET_AMOUNT
ORDER BY USED_RATE DESC

/* MEMBER_ID, BUDGET_MONTH */
