-- 카테고리 등록
INSERT INTO TBL_CATEGORY
VALUES (SEQ_CATEGORY.NEXTVAL, ?, ?, ?, SYSDATE, NULL)

/* MEMBER_ID, CATEGORY_NAME, CATEGORY_TYPE */



-- 내 카테고리 목록 조회
SELECT ID, MEMBER_ID, CATEGORY_NAME, CATEGORY_TYPE, CREATED_AT, UPDATED_AT
FROM TBL_CATEGORY
WHERE MEMBER_ID = ?
ORDER BY CATEGORY_TYPE, CATEGORY_NAME

/* MEMBER_ID */



-- 수입 지출별 카테고리 조회
SELECT ID, MEMBER_ID, CATEGORY_NAME, CATEGORY_TYPE
FROM TBL_CATEGORY
WHERE MEMBER_ID = ?
AND CATEGORY_TYPE = ?
ORDER BY CATEGORY_NAME

/* MEMBER_ID, CATEGORY_TYPE */



-- 특정 카테고리 조회
SELECT ID, MEMBER_ID, CATEGORY_NAME, CATEGORY_TYPE
FROM TBL_CATEGORY
WHERE ID = ?
AND MEMBER_ID = ?

/* CATEGORY_ID, MEMBER_ID */



-- 카테고리 수정
UPDATE TBL_CATEGORY
SET CATEGORY_NAME = ?,
    CATEGORY_TYPE = ?,
    UPDATED_AT = SYSDATE
WHERE ID = ?
AND MEMBER_ID = ?

/* CATEGORY_NAME, CATEGORY_TYPE, CATEGORY_ID, MEMBER_ID */



-- 카테고리 삭제
DELETE FROM TBL_CATEGORY
WHERE ID = ?
AND MEMBER_ID = ?

/* CATEGORY_ID, MEMBER_ID */
