DROP TABLE TBL_TRANSACTION;
DROP TABLE TBL_CATEGORY;
DROP TABLE TBL_ACCOUNT;
DROP TABLE TBL_MEMBER;

DROP SEQUENCE SEQ_TRANSACTION;
DROP SEQUENCE SEQ_CATEGORY;
DROP SEQUENCE SEQ_ACCOUNT;
DROP SEQUENCE SEQ_MEMBER;

CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER (
    ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
    MEMBER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
    MEMBER_NICKNAME VARCHAR2(100) NOT NULL,
    MEMBER_ROLE VARCHAR2(20) DEFAULT 'USER' CHECK (MEMBER_ROLE IN ('USER', 'ADMIN')),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE
);

CREATE SEQUENCE SEQ_ACCOUNT;

CREATE TABLE TBL_ACCOUNT (
    ID NUMBER CONSTRAINT PK_ACCOUNT PRIMARY KEY,
    MEMBER_ID NUMBER REFERENCES TBL_MEMBER(ID),
    BANK_NAME VARCHAR2(100) NOT NULL,
    ACCOUNT_NAME VARCHAR2(100) NOT NULL,
    ACCOUNT_NUMBER VARCHAR2(50) NOT NULL,
    BALANCE NUMBER DEFAULT 0 CHECK (BALANCE >= 0),
    ACCOUNT_STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (ACCOUNT_STATUS IN ('ACTIVE', 'DELETED')),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE
);

CREATE SEQUENCE SEQ_CATEGORY;

CREATE TABLE TBL_CATEGORY (
    ID NUMBER CONSTRAINT PK_CATEGORY PRIMARY KEY,
    MEMBER_ID NUMBER REFERENCES TBL_MEMBER(ID),
    CATEGORY_NAME VARCHAR2(100) NOT NULL,
    CATEGORY_TYPE VARCHAR2(20) CHECK (CATEGORY_TYPE IN ('INCOME', 'EXPENSE')),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE
);

CREATE SEQUENCE SEQ_TRANSACTION;

CREATE TABLE TBL_TRANSACTION (
    ID NUMBER CONSTRAINT PK_TRANSACTION PRIMARY KEY,
    ACCOUNT_ID NUMBER REFERENCES TBL_ACCOUNT(ID),
    CATEGORY_ID NUMBER REFERENCES TBL_CATEGORY(ID),
    TRANSACTION_TYPE VARCHAR2(20) CHECK (TRANSACTION_TYPE IN ('INCOME', 'EXPENSE')),
    AMOUNT NUMBER CHECK (AMOUNT > 0),
    TRANSACTION_DATE DATE DEFAULT SYSDATE,
    MEMO VARCHAR2(255),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE
);
