-- 회원가입
INSERT INTO TBL_MEMBER
VALUES (SEQ_MEMBER.NEXTVAL, ?, ?, ?, 'USER', SYSDATE, NULL)

/* MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NICKNAME */



-- 로그인 조회
SELECT ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NICKNAME, MEMBER_ROLE
FROM TBL_MEMBER
WHERE MEMBER_EMAIL = ?

/* MEMBER_EMAIL */



-- 회원 정보 조회
SELECT ID, MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_ROLE, CREATED_AT, UPDATED_AT
FROM TBL_MEMBER
WHERE ID = ?

/* MEMBER_ID */



-- 회원 닉네임 수정
UPDATE TBL_MEMBER
SET MEMBER_NICKNAME = ?,
    UPDATED_AT = SYSDATE
WHERE ID = ?

/* MEMBER_NICKNAME, MEMBER_ID */



-- 비밀번호 수정
UPDATE TBL_MEMBER
SET MEMBER_PASSWORD = ?,
    UPDATED_AT = SYSDATE
WHERE ID = ?

/* MEMBER_PASSWORD, MEMBER_ID */
