-- 이체 등록
INSERT INTO TBL_TRANSFER
VALUES (SEQ_TRANSFER.NEXTVAL, ?, ?, ?, ?, ?, SYSDATE)

/* FROM_ACCOUNT_ID, TO_ACCOUNT_ID, AMOUNT, TRANSFER_DATE, MEMO */



-- 내 전체 이체 내역 조회
SELECT TF.ID,
       TF.FROM_ACCOUNT_ID,
       FA.ACCOUNT_NAME AS FROM_ACCOUNT_NAME,
       TF.TO_ACCOUNT_ID,
       TA.ACCOUNT_NAME AS TO_ACCOUNT_NAME,
       TF.AMOUNT,
       TF.TRANSFER_DATE,
       TF.MEMO,
       TF.CREATED_AT
FROM TBL_TRANSFER TF
JOIN TBL_ACCOUNT FA
    ON TF.FROM_ACCOUNT_ID = FA.ID
JOIN TBL_ACCOUNT TA
    ON TF.TO_ACCOUNT_ID = TA.ID
WHERE FA.MEMBER_ID = ?
AND TA.MEMBER_ID = ?
ORDER BY TF.TRANSFER_DATE DESC, TF.ID DESC

/* MEMBER_ID, MEMBER_ID */



-- 특정 계좌 이체 내역 조회
SELECT TF.ID,
       TF.FROM_ACCOUNT_ID,
       FA.ACCOUNT_NAME AS FROM_ACCOUNT_NAME,
       TF.TO_ACCOUNT_ID,
       TA.ACCOUNT_NAME AS TO_ACCOUNT_NAME,
       TF.AMOUNT,
       TF.TRANSFER_DATE,
       TF.MEMO,
       TF.CREATED_AT
FROM TBL_TRANSFER TF
JOIN TBL_ACCOUNT FA
    ON TF.FROM_ACCOUNT_ID = FA.ID
JOIN TBL_ACCOUNT TA
    ON TF.TO_ACCOUNT_ID = TA.ID
WHERE (TF.FROM_ACCOUNT_ID = ? OR TF.TO_ACCOUNT_ID = ?)
AND FA.MEMBER_ID = ?
AND TA.MEMBER_ID = ?
ORDER BY TF.TRANSFER_DATE DESC, TF.ID DESC

/* ACCOUNT_ID, ACCOUNT_ID, MEMBER_ID, MEMBER_ID */



-- 특정 이체 조회
SELECT TF.ID,
       TF.FROM_ACCOUNT_ID,
       TF.TO_ACCOUNT_ID,
       TF.AMOUNT,
       TF.TRANSFER_DATE,
       TF.MEMO,
       TF.CREATED_AT
FROM TBL_TRANSFER TF
JOIN TBL_ACCOUNT FA
    ON TF.FROM_ACCOUNT_ID = FA.ID
JOIN TBL_ACCOUNT TA
    ON TF.TO_ACCOUNT_ID = TA.ID
WHERE TF.ID = ?
AND FA.MEMBER_ID = ?
AND TA.MEMBER_ID = ?

/* TRANSFER_ID, MEMBER_ID, MEMBER_ID */
