package com.app.wallet.query;

public class AccountQuery {

	public static final String INSERT_ACCOUNT = """
			INSERT INTO TBL_ACCOUNT
			VALUES (SEQ_ACCOUNT.NEXTVAL, ?, ?, ?, ?, ?, 'ACTIVE', SYSDATE, NULL)
			""";

	public static final String SELECT_ACCOUNTS_BY_MEMBER_ID = """
			SELECT ID, MEMBER_ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE, ACCOUNT_STATUS, CREATED_AT, UPDATED_AT
			FROM TBL_ACCOUNT
			WHERE MEMBER_ID = ?
			  AND ACCOUNT_STATUS = 'ACTIVE'
			ORDER BY ID
			""";

	public static final String SELECT_ACCOUNT_BY_ID = """
			SELECT ID, MEMBER_ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE, ACCOUNT_STATUS, CREATED_AT, UPDATED_AT
			FROM TBL_ACCOUNT
			WHERE ID = ?
			  AND MEMBER_ID = ?
			  AND ACCOUNT_STATUS = 'ACTIVE'
			""";

	public static final String UPDATE_ACCOUNT = """
			UPDATE TBL_ACCOUNT
			SET BANK_NAME = ?,
			    ACCOUNT_NAME = ?,
			    ACCOUNT_NUMBER = ?,
			    UPDATED_AT = SYSDATE
			WHERE ID = ?
			  AND MEMBER_ID = ?
			  AND ACCOUNT_STATUS = 'ACTIVE'
			""";

	public static final String DELETE_ACCOUNT_LOGICALLY = """
			UPDATE TBL_ACCOUNT
			SET ACCOUNT_STATUS = 'DELETED',
			    UPDATED_AT = SYSDATE
			WHERE ID = ?
			  AND MEMBER_ID = ?
			  AND ACCOUNT_STATUS = 'ACTIVE'
			""";

	public static final String UPDATE_BALANCE = """
			UPDATE TBL_ACCOUNT
			SET BALANCE = ?,
			    UPDATED_AT = SYSDATE
			WHERE ID = ?
			  AND MEMBER_ID = ?
			  AND ACCOUNT_STATUS = 'ACTIVE'
			""";

	public static final String SELECT_TOTAL_BALANCE = """
			SELECT NVL(SUM(BALANCE), 0) AS TOTAL_BALANCE
			FROM TBL_ACCOUNT
			WHERE MEMBER_ID = ?
			  AND ACCOUNT_STATUS = 'ACTIVE'
			""";
}
