package com.app.wallet.query;

public class AccountQuery {

	private AccountQuery() {
	}

	// 계좌 등록
	// MEMBER_ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE
	public static final String INSERT_ACCOUNT = """
			INSERT INTO TBL_ACCOUNT
			VALUES (SEQ_ACCOUNT.NEXTVAL, ?, ?, ?, ?, ?, 'ACTIVE', SYSDATE, NULL)
			""";

	// 내 계좌 목록 조회
	// MEMBER_ID
	public static final String SELECT_ACCOUNTS_BY_MEMBER_ID = """
			SELECT ID, MEMBER_ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER,
			       BALANCE, ACCOUNT_STATUS, CREATED_AT, UPDATED_AT
			FROM TBL_ACCOUNT
			WHERE MEMBER_ID = ?
			AND ACCOUNT_STATUS = 'ACTIVE'
			ORDER BY ID
			""";

	// 특정 계좌 조회
	// ACCOUNT_ID, MEMBER_ID
	public static final String SELECT_ACCOUNT_BY_ID = """
			SELECT ID, MEMBER_ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER,
			       BALANCE, ACCOUNT_STATUS, CREATED_AT, UPDATED_AT
			FROM TBL_ACCOUNT
			WHERE ID = ?
			AND MEMBER_ID = ?
			AND ACCOUNT_STATUS = 'ACTIVE'
			""";

	// 계좌 수정
	// BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, ACCOUNT_ID, MEMBER_ID
	public static final String UPDATE_ACCOUNT = """
			UPDATE TBL_ACCOUNT
			SET BANK_NAME = ?,
			    ACCOUNT_NAME = ?,
			    ACCOUNT_NUMBER = ?,
			    UPDATED_AT = SYSDATE
			WHERE ID = ?
			AND MEMBER_ID = ?
			AND ACCOUNT_STATUS = 'ACTIVE'
			""";

	// 계좌 삭제 처리
	// ACCOUNT_ID, MEMBER_ID
	public static final String DELETE_ACCOUNT_LOGICALLY = """
			UPDATE TBL_ACCOUNT
			SET ACCOUNT_STATUS = 'DELETED',
			    UPDATED_AT = SYSDATE
			WHERE ID = ?
			AND MEMBER_ID = ?
			AND ACCOUNT_STATUS = 'ACTIVE'
			""";

	// 계좌 잔액 증가
	// AMOUNT, ACCOUNT_ID, MEMBER_ID
	public static final String INCREASE_BALANCE = """
			UPDATE TBL_ACCOUNT
			SET BALANCE = BALANCE + ?,
			    UPDATED_AT = SYSDATE
			WHERE ID = ?
			AND MEMBER_ID = ?
			AND ACCOUNT_STATUS = 'ACTIVE'
			""";

	// 계좌 잔액 감소
	// AMOUNT, ACCOUNT_ID, MEMBER_ID, AMOUNT
	public static final String DECREASE_BALANCE = """
			UPDATE TBL_ACCOUNT
			SET BALANCE = BALANCE - ?,
			    UPDATED_AT = SYSDATE
			WHERE ID = ?
			AND MEMBER_ID = ?
			AND ACCOUNT_STATUS = 'ACTIVE'
			AND BALANCE >= ?
			""";

	// 내 전체 자산 잔액 조회
	// MEMBER_ID
	public static final String SELECT_TOTAL_BALANCE = """
			SELECT NVL(SUM(BALANCE), 0) AS TOTAL_BALANCE
			FROM TBL_ACCOUNT
			WHERE MEMBER_ID = ?
			AND ACCOUNT_STATUS = 'ACTIVE'
			""";

	// 계좌별 잔액 조회
	// MEMBER_ID
	public static final String SELECT_ACCOUNT_BALANCES = """
			SELECT ID, BANK_NAME, ACCOUNT_NAME, ACCOUNT_NUMBER, BALANCE
			FROM TBL_ACCOUNT
			WHERE MEMBER_ID = ?
			AND ACCOUNT_STATUS = 'ACTIVE'
			ORDER BY ID
			""";
}