package com.app.wallet.query;

public class TransactionQuery {

	private TransactionQuery() {
	}

	// 거래 등록
	// ACCOUNT_ID, CATEGORY_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_DATE, MEMO
	public static final String INSERT_TRANSACTION = """
			INSERT INTO TBL_TRANSACTION
			VALUES (SEQ_TRANSACTION.NEXTVAL, ?, ?, ?, ?, ?, ?, SYSDATE, NULL)
			""";

	// 내 전체 거래 목록 조회
	// MEMBER_ID
	public static final String SELECT_TRANSACTIONS_BY_MEMBER_ID = """
			SELECT T.ID,
			       T.ACCOUNT_ID,
			       A.ACCOUNT_NAME,
			       T.CATEGORY_ID,
			       C.CATEGORY_NAME,
			       T.TRANSACTION_TYPE,
			       T.AMOUNT,
			       T.TRANSACTION_DATE,
			       T.MEMO,
			       T.CREATED_AT,
			       T.UPDATED_AT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C
			    ON T.CATEGORY_ID = C.ID
			WHERE A.MEMBER_ID = ?
			ORDER BY T.TRANSACTION_DATE DESC, T.ID DESC
			""";

	// 특정 계좌 거래 목록 조회
	// MEMBER_ID, ACCOUNT_ID
	public static final String SELECT_TRANSACTIONS_BY_ACCOUNT_ID = """
			SELECT T.ID,
			       T.ACCOUNT_ID,
			       A.ACCOUNT_NAME,
			       T.CATEGORY_ID,
			       C.CATEGORY_NAME,
			       T.TRANSACTION_TYPE,
			       T.AMOUNT,
			       T.TRANSACTION_DATE,
			       T.MEMO,
			       T.CREATED_AT,
			       T.UPDATED_AT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C
			    ON T.CATEGORY_ID = C.ID
			WHERE A.MEMBER_ID = ?
			AND A.ID = ?
			ORDER BY T.TRANSACTION_DATE DESC, T.ID DESC
			""";

	// 특정 거래 조회
	// TRANSACTION_ID, MEMBER_ID
	public static final String SELECT_TRANSACTION_BY_ID = """
			SELECT T.ID,
			       T.ACCOUNT_ID,
			       T.CATEGORY_ID,
			       T.TRANSACTION_TYPE,
			       T.AMOUNT,
			       T.TRANSACTION_DATE,
			       T.MEMO,
			       A.MEMBER_ID
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			WHERE T.ID = ?
			AND A.MEMBER_ID = ?
			""";

	// 거래 수정
	// CATEGORY_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_DATE, MEMO, TRANSACTION_ID
	public static final String UPDATE_TRANSACTION = """
			UPDATE TBL_TRANSACTION
			SET CATEGORY_ID = ?,
			    TRANSACTION_TYPE = ?,
			    AMOUNT = ?,
			    TRANSACTION_DATE = ?,
			    MEMO = ?,
			    UPDATED_AT = SYSDATE
			WHERE ID = ?
			""";

	// 거래 삭제
	// TRANSACTION_ID
	public static final String DELETE_TRANSACTION = """
			DELETE FROM TBL_TRANSACTION
			WHERE ID = ?
			""";

	// 특정 월 수입 지출 순수익 조회
	// MEMBER_ID, YYYY-MM
	public static final String SELECT_MONTHLY_SUMMARY = """
			SELECT NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'INCOME' THEN T.AMOUNT ELSE 0 END), 0) AS MONTHLY_INCOME,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'EXPENSE' THEN T.AMOUNT ELSE 0 END), 0) AS MONTHLY_EXPENSE,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'INCOME' THEN T.AMOUNT ELSE -T.AMOUNT END), 0) AS MONTHLY_NET_AMOUNT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			WHERE A.MEMBER_ID = ?
			AND TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') = ?
			""";

	// 내 자산 카테고리별 조회
	// MEMBER_ID, YYYY-MM
	public static final String SELECT_CATEGORY_SUMMARY_BY_MEMBER_ID = """
			SELECT C.CATEGORY_NAME,
			       C.CATEGORY_TYPE,
			       SUM(T.AMOUNT) AS TOTAL_AMOUNT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C
			    ON T.CATEGORY_ID = C.ID
			WHERE A.MEMBER_ID = ?
			AND TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') = ?
			GROUP BY C.CATEGORY_NAME, C.CATEGORY_TYPE
			ORDER BY C.CATEGORY_TYPE, TOTAL_AMOUNT DESC
			""";

	// 내 자산 지출 카테고리별 조회
	// MEMBER_ID, YYYY-MM
	public static final String SELECT_EXPENSE_CATEGORY_SUMMARY_BY_MEMBER_ID = """
			SELECT C.CATEGORY_NAME,
			       SUM(T.AMOUNT) AS TOTAL_AMOUNT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C
			    ON T.CATEGORY_ID = C.ID
			WHERE A.MEMBER_ID = ?
			AND T.TRANSACTION_TYPE = 'EXPENSE'
			AND TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') = ?
			GROUP BY C.CATEGORY_NAME
			ORDER BY TOTAL_AMOUNT DESC
			""";

	// 특정 계좌 카테고리별 조회
	// MEMBER_ID, ACCOUNT_ID, YYYY-MM
	public static final String SELECT_CATEGORY_SUMMARY_BY_ACCOUNT_ID = """
			SELECT C.CATEGORY_NAME,
			       C.CATEGORY_TYPE,
			       SUM(T.AMOUNT) AS TOTAL_AMOUNT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C
			    ON T.CATEGORY_ID = C.ID
			WHERE A.MEMBER_ID = ?
			AND A.ID = ?
			AND TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') = ?
			GROUP BY C.CATEGORY_NAME, C.CATEGORY_TYPE
			ORDER BY C.CATEGORY_TYPE, TOTAL_AMOUNT DESC
			""";

	// 특정 계좌 지출 카테고리별 조회
	// MEMBER_ID, ACCOUNT_ID, YYYY-MM
	public static final String SELECT_EXPENSE_CATEGORY_SUMMARY_BY_ACCOUNT_ID = """
			SELECT C.CATEGORY_NAME,
			       SUM(T.AMOUNT) AS TOTAL_AMOUNT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C
			    ON T.CATEGORY_ID = C.ID
			WHERE A.MEMBER_ID = ?
			AND A.ID = ?
			AND T.TRANSACTION_TYPE = 'EXPENSE'
			AND TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') = ?
			GROUP BY C.CATEGORY_NAME
			ORDER BY TOTAL_AMOUNT DESC
			""";

	// 월별 수입 지출 요약 조회
	// MEMBER_ID
	public static final String SELECT_MONTHLY_SUMMARY_LIST = """
			SELECT TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') AS MONTH_VALUE,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'INCOME' THEN T.AMOUNT ELSE 0 END), 0) AS INCOME_AMOUNT,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'EXPENSE' THEN T.AMOUNT ELSE 0 END), 0) AS EXPENSE_AMOUNT,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'INCOME' THEN T.AMOUNT ELSE -T.AMOUNT END), 0) AS NET_AMOUNT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			WHERE A.MEMBER_ID = ?
			GROUP BY TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM')
			ORDER BY MONTH_VALUE DESC
			""";

	// 특정 계좌 월별 수입 지출 요약 조회
	// MEMBER_ID, ACCOUNT_ID
	public static final String SELECT_MONTHLY_SUMMARY_LIST_BY_ACCOUNT_ID = """
			SELECT TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') AS MONTH_VALUE,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'INCOME' THEN T.AMOUNT ELSE 0 END), 0) AS INCOME_AMOUNT,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'EXPENSE' THEN T.AMOUNT ELSE 0 END), 0) AS EXPENSE_AMOUNT,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'INCOME' THEN T.AMOUNT ELSE -T.AMOUNT END), 0) AS NET_AMOUNT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			WHERE A.MEMBER_ID = ?
			AND A.ID = ?
			GROUP BY TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM')
			ORDER BY MONTH_VALUE DESC
			""";

	// 기간별 거래 조회
	// MEMBER_ID, START_DATE, END_DATE
	public static final String SELECT_TRANSACTIONS_BY_PERIOD = """
			SELECT T.ID,
			       A.ACCOUNT_NAME,
			       C.CATEGORY_NAME,
			       T.TRANSACTION_TYPE,
			       T.AMOUNT,
			       T.TRANSACTION_DATE,
			       T.MEMO
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C
			    ON T.CATEGORY_ID = C.ID
			WHERE A.MEMBER_ID = ?
			AND T.TRANSACTION_DATE BETWEEN ? AND ?
			ORDER BY T.TRANSACTION_DATE DESC, T.ID DESC
			""";

	// 메모 키워드 검색
	// MEMBER_ID, KEYWORD
	public static final String SELECT_TRANSACTIONS_BY_MEMO_KEYWORD = """
			SELECT T.ID,
			       A.ACCOUNT_NAME,
			       C.CATEGORY_NAME,
			       T.TRANSACTION_TYPE,
			       T.AMOUNT,
			       T.TRANSACTION_DATE,
			       T.MEMO
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A
			    ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C
			    ON T.CATEGORY_ID = C.ID
			WHERE A.MEMBER_ID = ?
			AND T.MEMO LIKE '%' || ? || '%'
			ORDER BY T.TRANSACTION_DATE DESC, T.ID DESC
			""";
}