package com.app.wallet.query;

public class TransactionQuery {

	public static final String INSERT_TRANSACTION = """
			INSERT INTO TBL_TRANSACTION
			VALUES (SEQ_TRANSACTION.NEXTVAL, ?, ?, ?, ?, ?, ?, SYSDATE, NULL)
			""";

	public static final String SELECT_TRANSACTION_BASE = """
			SELECT T.ID,
			       T.ACCOUNT_ID,
			       A.ACCOUNT_NAME,
			       T.CATEGORY_ID,
			       C.CATEGORY_NAME,
			       T.TRANSACTION_TYPE,
			       T.AMOUNT,
			       T.TRANSACTION_DATE,
			       T.MEMO,
			       T.CREATED_AT,
			       T.UPDATED_AT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C ON T.CATEGORY_ID = C.ID
			""";

	public static final String SELECT_TRANSACTIONS_BY_MEMBER_ID = SELECT_TRANSACTION_BASE + """
			WHERE A.MEMBER_ID = ?
			  AND A.ACCOUNT_STATUS = 'ACTIVE'
			ORDER BY T.TRANSACTION_DATE DESC, T.ID DESC
			""";

	public static final String SELECT_TRANSACTIONS_BY_ACCOUNT_ID = SELECT_TRANSACTION_BASE + """
			WHERE A.MEMBER_ID = ?
			  AND A.ID = ?
			  AND A.ACCOUNT_STATUS = 'ACTIVE'
			ORDER BY T.TRANSACTION_DATE DESC, T.ID DESC
			""";

	public static final String SELECT_TRANSACTION_BY_ID = SELECT_TRANSACTION_BASE + """
			WHERE T.ID = ?
			  AND A.MEMBER_ID = ?
			  AND A.ACCOUNT_STATUS = 'ACTIVE'
			""";

	public static final String UPDATE_TRANSACTION = """
			UPDATE TBL_TRANSACTION
			SET CATEGORY_ID = ?,
			    TRANSACTION_TYPE = ?,
			    AMOUNT = ?,
			    TRANSACTION_DATE = ?,
			    MEMO = ?,
			    UPDATED_AT = SYSDATE
			WHERE ID = ?
			""";

	public static final String DELETE_TRANSACTION = """
			DELETE FROM TBL_TRANSACTION
			WHERE ID = ?
			""";

	public static final String SELECT_MONTHLY_SUMMARY = """
			SELECT TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') AS MONTH_VALUE,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'INCOME' THEN T.AMOUNT ELSE 0 END), 0) AS INCOME_AMOUNT,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'EXPENSE' THEN T.AMOUNT ELSE 0 END), 0) AS EXPENSE_AMOUNT,
			       NVL(SUM(CASE WHEN T.TRANSACTION_TYPE = 'INCOME' THEN T.AMOUNT ELSE -T.AMOUNT END), 0) AS NET_AMOUNT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A ON T.ACCOUNT_ID = A.ID
			WHERE A.MEMBER_ID = ?
			  AND A.ACCOUNT_STATUS = 'ACTIVE'
			GROUP BY TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM')
			ORDER BY MONTH_VALUE DESC
			""";

	public static final String SELECT_CATEGORY_SUMMARY = """
			SELECT C.CATEGORY_NAME,
			       C.CATEGORY_TYPE,
			       NVL(SUM(T.AMOUNT), 0) AS TOTAL_AMOUNT
			FROM TBL_TRANSACTION T
			JOIN TBL_ACCOUNT A ON T.ACCOUNT_ID = A.ID
			JOIN TBL_CATEGORY C ON T.CATEGORY_ID = C.ID
			WHERE A.MEMBER_ID = ?
			  AND A.ACCOUNT_STATUS = 'ACTIVE'
			  AND TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM') = ?
			GROUP BY C.CATEGORY_NAME, C.CATEGORY_TYPE
			ORDER BY C.CATEGORY_TYPE, TOTAL_AMOUNT DESC
			""";
}
